steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build-docker
  dir: 'Docker/bismark'
  args: ['build', '-t', 'gcr.io/aryeelab/bismark:$SHORT_SHA', '-t', 'gcr.io/aryeelab/bismark:latest', '--build-arg', 'VERSION=$SHORT_SHA', '.']

images: ['gcr.io/aryeelab/bismark']
timeout: 3600s
